
source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '8.0'

target 'DMMessageHUD_Example' do
    pod 'DMMessageHUD', :path => '../'
    
    pod 'Masonry', '~> 0.6.4'
    
    
    target 'DMMessageHUD_Tests' do
        inherit! :search_paths
        
        
    end
end
